
AddModule "edge-tts-generic" "sd_generic" "edge-tts-generic.conf"

DefaultModule "edge-tts-generic"

# Prefer edge-tts for Chinese
LanguageDefaultModule "zh"    "edge-tts-generic"
LanguageDefaultModule "zh-CN" "edge-tts-generic"
LanguageDefaultModule "zh-HK" "edge-tts-generic"
LanguageDefaultModule "zh-TW" "edge-tts-generic"

AudioOutputMethod "pipewire"
